name: clock_widget
description: A flutter package to displays a clock widget with real time.
version: 0.0.3
homepage: https://github.com/deb-sahu/clock_widget

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0